stages:
  - build
  - deploy

build-other:
  stage: build
  script:
    - docker build .
  except:
    - master

build-master:
  stage: build
  script:
    - REV=${CI_PIPELINE_IID}_${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA:0:7}
    - APP=asapixel
    - IMG="registry.activitystream.com:5043/${APP}"
    - docker build -t ${IMG}:${REV} .
    - docker tag ${APP}:${REV} ${IMG}:latest
    - docker push ${IMG}:${REV}
    - docker push ${IMG}:latest

  only:
    - master

deploy-to-swarm:
  stage: deploy
  variables:
    DOCKER_HOST: "tcp://prodmanager2-int.activitystream.com:2376"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "~/.docker"
  image: docker:latest
  script:
    - mkdir -p "${DOCKER_CERT_PATH}"
    - echo "$TLSCACERT" > "${DOCKER_CERT_PATH}/ca.pem"
    - echo "$TLSCERT" > "${DOCKER_CERT_PATH}/cert.pem"
    - echo "$TLSKEY" > "${DOCKER_CERT_PATH}/key.pem"
    - export PIXEL_REV=${CI_PIPELINE_IID}_${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA:0:7}
    - docker stack deploy -c docker-stack.yml --with-registry-auth pixel
  environment:
    name: prod
    url: http://pixel.activitystream.com
  only:
    - master